name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or your chosen branch for deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Install dependencies and build
        run: |
          npm install --legacy-peer-deps
          npm run build  # This will now create the 'out' folder
      
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # deployment branch
          folder: out       # path to the static output folder
